version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh 192.128.1.201:27017 -- pm2-runtime start ecosystem.config.js --env production
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
    networks:
      lhbridge:
        ipv4_address: 192.128.1.200
  mongo:
    image: mongo
    restart: always
    ports:
      - 27021:27017
    volumes:
      - ./data:/data/db
    networks:
      lhbridge:
        ipv4_address: 192.128.1.201
networks:
  lhbridge:
    external:
      name: lhbridge
