version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh ${MONGO_IP}:27017 -- pm2-runtime start ecosystem.config.js --env production
    env_file:
      - .env
    ports:
      - ${NODE_PORT}:3000
    depends_on:
      - mongo
    restart: always
    networks:
      lhbridge:
        ipv4_address: ${NODE_IP}
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    networks:
      lhbridge:
        ipv4_address: ${MONGO_IP}
networks:
  lhbridge:
    external:
      name: lhbridge
